<?php


?>
<html>
<head>
<title>Registrati</title>

</head>

<body>
    <form id="registrati" name="registrati" action="registrati.php" method="POST">
        <table border="0" cellspacing="5" cellpadding="5">
        <tr>
            <td>Nome</td>
            <td><input type="text" id="firstname" name="firstname" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td>Cognome</td>
            <td><input type="text" id="lastname" name="lastname" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="text" id="email" name="email" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="text" id="pwd" name="pwd" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td>Ripeti Password</td>
            <td><input type="text" id="pwd2" name="pwd2" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td>Città</td>
            <td><input type="text" id="city" name="city" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td>Stato</td>
            <td><input type="text" id="state" name="state" size="35" maxlength="40" value=""></td>
        </tr>
        <tr>
            <td></td>
            <td><input type=submit value="Registrati"><input type=reset value="Svuota"></td>
        </tr>
</table>
</form> 

<?php /*
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
<script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
<script>
jQuery.validator.setDefaults({
  debug: true,
  success: "valid"
});
$( "#registrati" ).validate({
  rules: {
    pwd: "required",
    pwd2: {
      equalTo: "#pwd"
    }
  }
});
</script>
*/
?>

</body>
</html>
